repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-ast

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: poetry run ruff --fix .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false
